services:
  app:
    build: .
    init: true
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped
    
    
    
👉 docker compose
docker compose up
docker compose down
